// Some packages need to compile third-party non-Rust code,
// for example C libraries. Other packages need to link to C libraries
// which can either be located on the system or possibly need to be built from source.
// Others still need facilities for functionality such as code generation before building (think parser generators).

// Cargo does not aim to replace other tools that are well-optimized for these tasks,
// but it does integrate with them with custom build scripts.
// Placing a file named build.rs in the root of a package will cause Cargo to compile that script and execute it just before building the package.

use std::fs::{read_dir, File};
use std::io::{Result, Write};

const USER_CRATE_DIR_NAME: &str = "../frontier_user";

fn main() {
    let target = std::env::var("TARGET").unwrap();
    let target_path = format!("{}/target/{}/release/", USER_CRATE_DIR_NAME, &target,);
    println!("cargo:rerun-if-changed={}/src/", USER_CRATE_DIR_NAME);
    println!("cargo:rerun-if-changed={}", &target_path);
    insert_app_data(&target_path).unwrap();
}

fn insert_app_data(target_path: &str) -> Result<()> {
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let mut f = File::create(format!("./src/assembly/{}/link_app.asm", arch))?;
    let mut apps: Vec<_> = read_dir(format!("{}/src/bin", USER_CRATE_DIR_NAME))?
        .into_iter()
        .map(|dir_entry| {
            let mut name_with_ext = dir_entry.unwrap().file_name().into_string().unwrap();
            name_with_ext.drain(name_with_ext.find('.').unwrap()..name_with_ext.len());
            name_with_ext
        })
        .collect();
    apps.sort();

    writeln!(
        f,
        r"
// ****************** this assembly file was generated by build.rs ******************
// ****************** do not change it !!!!!!!!!!!!!!!!!!!!!!!!!  ******************
    .align 4
    .section .data
    .global _addr_app_count
    .global _app_names
_addr_app_count:
    .quad {}",
        apps.len()
    )?;

    for i in 0..apps.len() {
        writeln!(f, r#"    .quad app_{}_start"#, i)?;
        writeln!(f, r#"    .quad app_{}_end"#, i)?;
    }

    writeln!(f, r#"_app_names:"#)?;
    for app in apps.iter() {
        writeln!(f, r#"    .string "{}""#, app)?;
    }

    for (idx, app) in apps.iter().enumerate() {
        println!("app_{}: {}", idx, app);
        writeln!(
            f,
            r#"
    .section .data
    .global app_{0}_start
    .global app_{0}_end
    .align 4
app_{0}_start:
    .incbin "{2}{1}"
app_{0}_end:"#,
            idx, app, target_path
        )?;
    }
    Ok(())
}
