
// ****************** this assembly file was generated by build.rs ******************
// ****************** do not change it !!!!!!!!!!!!!!!!!!!!!!!!!  ******************
    .align 4
    .section .data
    .global _addr_app_count
    .global _app_names
_addr_app_count:
    .quad 17
    .quad app_0_start
    .quad app_0_end
    .quad app_1_start
    .quad app_1_end
    .quad app_2_start
    .quad app_2_end
    .quad app_3_start
    .quad app_3_end
    .quad app_4_start
    .quad app_4_end
    .quad app_5_start
    .quad app_5_end
    .quad app_6_start
    .quad app_6_end
    .quad app_7_start
    .quad app_7_end
    .quad app_8_start
    .quad app_8_end
    .quad app_9_start
    .quad app_9_end
    .quad app_10_start
    .quad app_10_end
    .quad app_11_start
    .quad app_11_end
    .quad app_12_start
    .quad app_12_end
    .quad app_13_start
    .quad app_13_end
    .quad app_14_start
    .quad app_14_end
    .quad app_15_start
    .quad app_15_end
    .quad app_16_start
    .quad app_16_end
_app_names:
    .string "core_shell"
    .string "exit_test"
    .string "fantastic_text"
    .string "forkexec"
    .string "forktest"
    .string "forktest2"
    .string "forktest_simple"
    .string "forktree"
    .string "hello_world"
    .string "initproc"
    .string "matrix"
    .string "sleep"
    .string "sleep_simple"
    .string "stack_overflow"
    .string "usertests"
    .string "usertests-simple"
    .string "yield_out"

    .section .data
    .global app_0_start
    .global app_0_end
    .align 4
app_0_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/core_shell"
app_0_end:

    .section .data
    .global app_1_start
    .global app_1_end
    .align 4
app_1_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/exit_test"
app_1_end:

    .section .data
    .global app_2_start
    .global app_2_end
    .align 4
app_2_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/fantastic_text"
app_2_end:

    .section .data
    .global app_3_start
    .global app_3_end
    .align 4
app_3_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/forkexec"
app_3_end:

    .section .data
    .global app_4_start
    .global app_4_end
    .align 4
app_4_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/forktest"
app_4_end:

    .section .data
    .global app_5_start
    .global app_5_end
    .align 4
app_5_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/forktest2"
app_5_end:

    .section .data
    .global app_6_start
    .global app_6_end
    .align 4
app_6_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/forktest_simple"
app_6_end:

    .section .data
    .global app_7_start
    .global app_7_end
    .align 4
app_7_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/forktree"
app_7_end:

    .section .data
    .global app_8_start
    .global app_8_end
    .align 4
app_8_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/hello_world"
app_8_end:

    .section .data
    .global app_9_start
    .global app_9_end
    .align 4
app_9_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/initproc"
app_9_end:

    .section .data
    .global app_10_start
    .global app_10_end
    .align 4
app_10_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/matrix"
app_10_end:

    .section .data
    .global app_11_start
    .global app_11_end
    .align 4
app_11_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/sleep"
app_11_end:

    .section .data
    .global app_12_start
    .global app_12_end
    .align 4
app_12_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/sleep_simple"
app_12_end:

    .section .data
    .global app_13_start
    .global app_13_end
    .align 4
app_13_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/stack_overflow"
app_13_end:

    .section .data
    .global app_14_start
    .global app_14_end
    .align 4
app_14_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/usertests"
app_14_end:

    .section .data
    .global app_15_start
    .global app_15_end
    .align 4
app_15_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/usertests-simple"
app_15_end:

    .section .data
    .global app_16_start
    .global app_16_end
    .align 4
app_16_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/yield_out"
app_16_end:
