
// ****************** this assembly file was generated by build.rs ******************
// ****************** do not change it !!!!!!!!!!!!!!!!!!!!!!!!!  ******************
    .align 3
    .section .data
    .global _addr_app_count
_addr_app_count:
    .quad 6
    .quad app_0_start
    .quad app_1_start
    .quad app_2_start
    .quad app_3_start
    .quad app_4_start
    .quad app_5_start
    .quad app_5_end

    .section .data
    .align 3
    .global app_0_start
    .global app_0_end
app_0_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/00_hello_world"
app_0_end:

    .section .data
    .align 3
    .global app_1_start
    .global app_1_end
app_1_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/01_store_fault"
app_1_end:

    .section .data
    .align 3
    .global app_2_start
    .global app_2_end
app_2_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/02_power"
app_2_end:

    .section .data
    .align 3
    .global app_3_start
    .global app_3_end
app_3_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/03_priv_inst"
app_3_end:

    .section .data
    .align 3
    .global app_4_start
    .global app_4_end
app_4_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/04_priv_csr"
app_4_end:

    .section .data
    .align 3
    .global app_5_start
    .global app_5_end
app_5_start:
    .incbin "../frontier_user/target/riscv64gc-unknown-none-elf/release/05_sleep"
app_5_end:
